Feature 2
shinonome-inc/lossless_challenge_ryo pull request #14
Opened 2020-07-12 07:20 UTC by Sota6174

subとupのフィルターとdic.pyを読み込んでself._imageに代入まで出来ました。
符号化はndarrayの形ではなく、１と０が一列にただ並んでるだけの状態にすることですか？

2020-07-12 11:02 UTC, rmasutani commented
お疲れ様！以下がレビューです

- issueを分けているのはレビューをしやすくするためなので、一つのプルリクで他のissueのコミットもするのは避けましょう。今回のケースで言えばdic.pyの読み込みに関してのコミットはfeature-1のブランチで行ってください。

- Encoderの__init__について`self._imgfilter = self._image`このままだと存在しない変数を代入することになってしまう

- encode関数の中身で、冒頭に_imgfilterを更新したにも関わらずその下のループで使われていない

- filter.pyで定義されている関数はクラスメソッドではないのでselfを引数にとる必要はないです。なので必然的にself._imgfilterというアクセス方法は変えないといけなくなります。というかfilterをかける前にすでに変数名がimgfilterなのは適切ではないような気がします。

- Tipが一つ。filter関数の中で256で割った余りを求めてくれてますが、inputとして渡される画像が入っているnumpyの配列は差がマイナスになると勝手にこれをやってくれるので実は必要ないです。一度numpyの配列やdtypeについて調べてもらった方が良い気がします

- 「符号化」についてはその認識であってます。自分が言葉足らずでした

2020-07-12 11:03 UTC, rmasutani requested changes
お疲れ様！以下がレビューです

- issueを分けているのはレビューをしやすくするためなので、一つのプルリクで他のissueのコミットもするのは避けましょう。今回のケースで言えばdic.pyの読み込みに関してのコミットはfeature-1のブランチで行ってください。

- Encoderの__init__について`self._imgfilter = self._image`このままだと存在しない変数を代入することになってしまう

- encode関数の中身で、冒頭に_imgfilterを更新したにも関わらずその下のループで使われていない

- filter.pyで定義されている関数はクラスメソッドではないのでselfを引数にとる必要はないです。なので必然的にself._imgfilterというアクセス方法は変えないといけなくなります。というかfilterをかける前にすでに変数名がimgfilterなのは適切ではないような気がします。

- Tipが一つ。filter関数の中で256で割った余りを求めてくれてますが、inputとして渡される画像が入っているnumpyの配列は差がマイナスになると勝手にこれをやってくれるので実は必要ないです。一度numpyの配列やdtypeについて調べてもらった方が良い気がします

- 「符号化」についてはその認識であってます。自分が言葉足らずでした

2020-07-14 05:01 UTC, rmasutani requested changes
レビューしたところはほぼ直せているし、docstringもしっかり書けていて素晴らしいです。ただ直して欲しいところが一つあります


sub, upのフィルターの関数はparameterのarrayを`array[y][x] = int(array[y][x]) - int(array[y-1][x])`という形で直接変更していますが、このままだと正しくフィルターはかけられません。加えてpythonでは配列は「参照渡し」なのでこの関数を入力画像に対して実行すると元の画像も変更されてしまいます。新しい配列を作ってその配列を返すようにしましょう。

ちなみにnp.ndarrayはdtypeが予め決まっている（今回のケースではnp.uint8）のでintを使う必要は無いです。

2020-07-14 11:30 UTC, Sota6174 commented
array[y][x] - array[y-1][x] をするとoverflow encountered in ubyte_scalars と言われたのでint型にしてから引いたのですが、このエラー？警告？は無視するという事ですか？

2020-07-14 12:07 UTC, Sota6174 commented
レビューを正しく反映出来てるか分かりませんが修正しました。
確認お願いします

2020-07-15 08:59 UTC, rmasutani requested changes
filter.pyのレビュー

np.zeros()で初期化してくれてますが、このままだと一行目/一列目に０でない画素があったときに画像が復元不可能になります。それと初期化のサイズが間違ってます。

加えて今はfilterをグローバルに定義してますが、このままだと全ての関数でfilterをシェアすることになるのでそれは避けたいです（複数のフィルターを一枚の画像に対して適用することもあるので）

あとdocstringには変数の説明とreturnについても書きましょう

2020-07-25 06:38 UTC, merged